# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(495, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.masterSystem = QtWidgets.QGroupBox(self.centralwidget)
        self.masterSystem.setGeometry(QtCore.QRect(10, 0, 231, 291))
        self.masterSystem.setTitle("")
        self.masterSystem.setObjectName("masterSystem")
        self.master_profile = QtWidgets.QComboBox(self.masterSystem)
        self.master_profile.setGeometry(QtCore.QRect(10, 50, 111, 32))
        self.master_profile.setObjectName("master_profile")
        self.master_profile.addItem("")
        self.master_profile.addItem("")
        self.run_master = QtWidgets.QPushButton(self.masterSystem)
        self.run_master.setGeometry(QtCore.QRect(140, 50, 81, 34))
        self.run_master.setObjectName("run_master")
        self.master_bin = QtWidgets.QSpinBox(self.masterSystem)
        self.master_bin.setGeometry(QtCore.QRect(140, 190, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.master_bin.setFont(font)
        self.master_bin.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.master_bin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.master_bin.setMinimum(1)
        self.master_bin.setMaximum(4)
        self.master_bin.setProperty("value", 1)
        self.master_bin.setObjectName("master_bin")
        self.label_39 = QtWidgets.QLabel(self.masterSystem)
        self.label_39.setGeometry(QtCore.QRect(10, 220, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.masterSystem)
        self.label_40.setGeometry(QtCore.QRect(10, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_163 = QtWidgets.QLabel(self.masterSystem)
        self.label_163.setGeometry(QtCore.QRect(10, 150, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_163.setFont(font)
        self.label_163.setObjectName("label_163")
        self.line_25 = QtWidgets.QFrame(self.masterSystem)
        self.line_25.setGeometry(QtCore.QRect(10, 170, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_25.setFont(font)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setObjectName("line_25")
        self.master_host = QtWidgets.QLineEdit(self.masterSystem)
        self.master_host.setGeometry(QtCore.QRect(10, 110, 111, 32))
        self.master_host.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.master_host.setObjectName("master_host")
        self.master_port = QtWidgets.QLineEdit(self.masterSystem)
        self.master_port.setGeometry(QtCore.QRect(140, 110, 81, 32))
        self.master_port.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.master_port.setObjectName("master_port")
        self.label_165 = QtWidgets.QLabel(self.masterSystem)
        self.label_165.setGeometry(QtCore.QRect(10, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_165.setFont(font)
        self.label_165.setObjectName("label_165")
        self.label_166 = QtWidgets.QLabel(self.masterSystem)
        self.label_166.setGeometry(QtCore.QRect(140, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_166.setFont(font)
        self.label_166.setObjectName("label_166")
        self.master_single_exposure = QtWidgets.QSpinBox(self.masterSystem)
        self.master_single_exposure.setGeometry(QtCore.QRect(140, 220, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.master_single_exposure.setFont(font)
        self.master_single_exposure.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.master_single_exposure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.master_single_exposure.setMinimum(0)
        self.master_single_exposure.setMaximum(10000000)
        self.master_single_exposure.setProperty("value", 10)
        self.master_single_exposure.setObjectName("master_single_exposure")
        self.label_41 = QtWidgets.QLabel(self.masterSystem)
        self.label_41.setGeometry(QtCore.QRect(10, 250, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.dither_every = QtWidgets.QSpinBox(self.masterSystem)
        self.dither_every.setGeometry(QtCore.QRect(140, 250, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dither_every.setFont(font)
        self.dither_every.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.dither_every.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dither_every.setMinimum(0)
        self.dither_every.setMaximum(100)
        self.dither_every.setProperty("value", 1)
        self.dither_every.setObjectName("dither_every")
        self.label = QtWidgets.QLabel(self.masterSystem)
        self.label.setGeometry(QtCore.QRect(10, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 290, 471, 251))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.integration_time = QtWidgets.QSpinBox(self.groupBox)
        self.integration_time.setGeometry(QtCore.QRect(130, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.integration_time.setFont(font)
        self.integration_time.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.integration_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.integration_time.setMinimum(30)
        self.integration_time.setMaximum(10000000)
        self.integration_time.setProperty("value", 300)
        self.integration_time.setObjectName("integration_time")
        self.label_42 = QtWidgets.QLabel(self.groupBox)
        self.label_42.setGeometry(QtCore.QRect(10, 55, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.object_name = QtWidgets.QLineEdit(self.groupBox)
        self.object_name.setGeometry(QtCore.QRect(60, 130, 161, 32))
        self.object_name.setObjectName("object_name")
        self.label_175 = QtWidgets.QLabel(self.groupBox)
        self.label_175.setGeometry(QtCore.QRect(10, 90, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_175.setFont(font)
        self.label_175.setObjectName("label_175")
        self.line_29 = QtWidgets.QFrame(self.groupBox)
        self.line_29.setGeometry(QtCore.QRect(10, 110, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_29.setFont(font)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setObjectName("line_29")
        self.label_51 = QtWidgets.QLabel(self.groupBox)
        self.label_51.setGeometry(QtCore.QRect(20, 130, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.ar = QtWidgets.QLineEdit(self.groupBox)
        self.ar.setGeometry(QtCore.QRect(60, 170, 161, 32))
        self.ar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ar.setObjectName("ar")
        self.label_52 = QtWidgets.QLabel(self.groupBox)
        self.label_52.setGeometry(QtCore.QRect(20, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox)
        self.label_53.setGeometry(QtCore.QRect(20, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.dec = QtWidgets.QLineEdit(self.groupBox)
        self.dec.setGeometry(QtCore.QRect(60, 210, 161, 32))
        self.dec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dec.setObjectName("dec")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(130, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.start = QtWidgets.QPushButton(self.groupBox)
        self.start.setGeometry(QtCore.QRect(340, 190, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.slaveSystem = QtWidgets.QGroupBox(self.centralwidget)
        self.slaveSystem.setGeometry(QtCore.QRect(250, 0, 231, 291))
        self.slaveSystem.setTitle("")
        self.slaveSystem.setObjectName("slaveSystem")
        self.slave_profile = QtWidgets.QComboBox(self.slaveSystem)
        self.slave_profile.setGeometry(QtCore.QRect(10, 50, 111, 32))
        self.slave_profile.setObjectName("slave_profile")
        self.slave_profile.addItem("")
        self.slave_profile.addItem("")
        self.run_slave = QtWidgets.QPushButton(self.slaveSystem)
        self.run_slave.setGeometry(QtCore.QRect(140, 50, 81, 34))
        self.run_slave.setObjectName("run_slave")
        self.slave_bin = QtWidgets.QSpinBox(self.slaveSystem)
        self.slave_bin.setGeometry(QtCore.QRect(140, 190, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.slave_bin.setFont(font)
        self.slave_bin.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.slave_bin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slave_bin.setMinimum(1)
        self.slave_bin.setMaximum(4)
        self.slave_bin.setProperty("value", 1)
        self.slave_bin.setObjectName("slave_bin")
        self.label_49 = QtWidgets.QLabel(self.slaveSystem)
        self.label_49.setGeometry(QtCore.QRect(10, 220, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.slaveSystem)
        self.label_50.setGeometry(QtCore.QRect(10, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_172 = QtWidgets.QLabel(self.slaveSystem)
        self.label_172.setGeometry(QtCore.QRect(10, 150, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_172.setFont(font)
        self.label_172.setObjectName("label_172")
        self.line_28 = QtWidgets.QFrame(self.slaveSystem)
        self.line_28.setGeometry(QtCore.QRect(10, 170, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_28.setFont(font)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setObjectName("line_28")
        self.slave_host = QtWidgets.QLineEdit(self.slaveSystem)
        self.slave_host.setGeometry(QtCore.QRect(10, 110, 111, 32))
        self.slave_host.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slave_host.setObjectName("slave_host")
        self.slave_port = QtWidgets.QLineEdit(self.slaveSystem)
        self.slave_port.setGeometry(QtCore.QRect(140, 110, 81, 32))
        self.slave_port.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slave_port.setObjectName("slave_port")
        self.label_173 = QtWidgets.QLabel(self.slaveSystem)
        self.label_173.setGeometry(QtCore.QRect(10, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_173.setFont(font)
        self.label_173.setObjectName("label_173")
        self.label_174 = QtWidgets.QLabel(self.slaveSystem)
        self.label_174.setGeometry(QtCore.QRect(140, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_174.setFont(font)
        self.label_174.setObjectName("label_174")
        self.slave_single_exposure = QtWidgets.QSpinBox(self.slaveSystem)
        self.slave_single_exposure.setGeometry(QtCore.QRect(140, 220, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.slave_single_exposure.setFont(font)
        self.slave_single_exposure.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.slave_single_exposure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slave_single_exposure.setMinimum(0)
        self.slave_single_exposure.setMaximum(10000000)
        self.slave_single_exposure.setProperty("value", 5)
        self.slave_single_exposure.setObjectName("slave_single_exposure")
        self.label_4 = QtWidgets.QLabel(self.slaveSystem)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 495, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_SaaS = QtWidgets.QAction(MainWindow)
        self.actionAbout_SaaS.setObjectName("actionAbout_SaaS")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout_SaaS)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.master_profile.setCurrentIndex(0)
        self.slave_profile.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SaaS for CCDCiel"))
        self.master_profile.setItemText(0, _translate("MainWindow", "QHY42"))
        self.master_profile.setItemText(1, _translate("MainWindow", "QHY268"))
        self.run_master.setText(_translate("MainWindow", "Run"))
        self.master_bin.setToolTip(_translate("MainWindow", "sets the camera bin"))
        self.label_39.setText(_translate("MainWindow", "Single exposure (s)"))
        self.label_40.setText(_translate("MainWindow", "Camera bin"))
        self.label_163.setText(_translate("MainWindow", "Frame settings"))
        self.master_host.setText(_translate("MainWindow", "localhost"))
        self.master_port.setText(_translate("MainWindow", "3277"))
        self.label_165.setText(_translate("MainWindow", "Server"))
        self.label_166.setText(_translate("MainWindow", "Port"))
        self.master_single_exposure.setToolTip(_translate("MainWindow", "sets the exposure time"))
        self.label_41.setText(_translate("MainWindow", "Dither (frames)"))
        self.dither_every.setToolTip(_translate("MainWindow", "sets the exposure time"))
        self.label.setText(_translate("MainWindow", "Master Node"))
        self.integration_time.setToolTip(_translate("MainWindow", "sets the camera bin"))
        self.label_42.setText(_translate("MainWindow", "Integration (s)"))
        self.label_175.setText(_translate("MainWindow", "Target properties"))
        self.label_51.setText(_translate("MainWindow", "Name"))
        self.ar.setText(_translate("MainWindow", "00:00:00"))
        self.label_52.setText(_translate("MainWindow", "AR"))
        self.label_53.setText(_translate("MainWindow", "DEC"))
        self.dec.setText(_translate("MainWindow", "00:00:00"))
        self.label_5.setText(_translate("MainWindow", "Sequence"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.slave_profile.setItemText(0, _translate("MainWindow", "QHY42"))
        self.slave_profile.setItemText(1, _translate("MainWindow", "QHY268"))
        self.run_slave.setText(_translate("MainWindow", "Run"))
        self.slave_bin.setToolTip(_translate("MainWindow", "sets the camera bin"))
        self.label_49.setText(_translate("MainWindow", "Single exposure (s)"))
        self.label_50.setText(_translate("MainWindow", "Camera bin"))
        self.label_172.setText(_translate("MainWindow", "Frame settings"))
        self.slave_host.setText(_translate("MainWindow", "localhost"))
        self.slave_port.setText(_translate("MainWindow", "3277"))
        self.label_173.setText(_translate("MainWindow", "Server"))
        self.label_174.setText(_translate("MainWindow", "Port"))
        self.slave_single_exposure.setToolTip(_translate("MainWindow", "sets the exposure time"))
        self.label_4.setText(_translate("MainWindow", "Slave Node"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionAbout_SaaS.setText(_translate("MainWindow", "&About SaaS"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
