# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 827)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(942, 827))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.masterSystem = QtWidgets.QGroupBox(self.centralwidget)
        self.masterSystem.setGeometry(QtCore.QRect(0, 100, 470, 591))
        self.masterSystem.setObjectName("masterSystem")
        self.master_profile = QtWidgets.QComboBox(self.masterSystem)
        self.master_profile.setGeometry(QtCore.QRect(10, 82, 101, 32))
        self.master_profile.setObjectName("master_profile")
        self.master_profile.addItem("")
        self.master_profile.addItem("")
        self.run_master = QtWidgets.QPushButton(self.masterSystem)
        self.run_master.setGeometry(QtCore.QRect(120, 82, 101, 32))
        self.run_master.setObjectName("run_master")
        self.master_bin = QtWidgets.QSpinBox(self.masterSystem)
        self.master_bin.setGeometry(QtCore.QRect(380, 72, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.master_bin.setFont(font)
        self.master_bin.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.master_bin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.master_bin.setMinimum(1)
        self.master_bin.setMaximum(4)
        self.master_bin.setProperty("value", 1)
        self.master_bin.setObjectName("master_bin")
        self.label_39 = QtWidgets.QLabel(self.masterSystem)
        self.label_39.setGeometry(QtCore.QRect(250, 102, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.masterSystem)
        self.label_40.setGeometry(QtCore.QRect(250, 72, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_163 = QtWidgets.QLabel(self.masterSystem)
        self.label_163.setGeometry(QtCore.QRect(250, 40, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_163.setFont(font)
        self.label_163.setObjectName("label_163")
        self.line_25 = QtWidgets.QFrame(self.masterSystem)
        self.line_25.setGeometry(QtCore.QRect(250, 55, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_25.setFont(font)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setObjectName("line_25")
        self.master_host = QtWidgets.QLineEdit(self.masterSystem)
        self.master_host.setGeometry(QtCore.QRect(10, 142, 101, 32))
        self.master_host.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.master_host.setObjectName("master_host")
        self.master_port = QtWidgets.QLineEdit(self.masterSystem)
        self.master_port.setGeometry(QtCore.QRect(120, 142, 101, 32))
        self.master_port.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.master_port.setObjectName("master_port")
        self.label_165 = QtWidgets.QLabel(self.masterSystem)
        self.label_165.setGeometry(QtCore.QRect(10, 122, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_165.setFont(font)
        self.label_165.setObjectName("label_165")
        self.label_166 = QtWidgets.QLabel(self.masterSystem)
        self.label_166.setGeometry(QtCore.QRect(120, 122, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_166.setFont(font)
        self.label_166.setObjectName("label_166")
        self.master_single_exposure = QtWidgets.QSpinBox(self.masterSystem)
        self.master_single_exposure.setGeometry(QtCore.QRect(380, 102, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.master_single_exposure.setFont(font)
        self.master_single_exposure.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.master_single_exposure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.master_single_exposure.setMinimum(0)
        self.master_single_exposure.setMaximum(10000000)
        self.master_single_exposure.setProperty("value", 10)
        self.master_single_exposure.setObjectName("master_single_exposure")
        self.label_41 = QtWidgets.QLabel(self.masterSystem)
        self.label_41.setGeometry(QtCore.QRect(250, 132, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.dither_every = QtWidgets.QSpinBox(self.masterSystem)
        self.dither_every.setGeometry(QtCore.QRect(380, 132, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dither_every.setFont(font)
        self.dither_every.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.dither_every.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dither_every.setMinimum(0)
        self.dither_every.setMaximum(100)
        self.dither_every.setProperty("value", 1)
        self.dither_every.setObjectName("dither_every")
        self.fo_2 = QtWidgets.QLabel(self.masterSystem)
        self.fo_2.setGeometry(QtCore.QRect(250, 162, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fo_2.setFont(font)
        self.fo_2.setObjectName("fo_2")
        self.focus_every_master = QtWidgets.QSpinBox(self.masterSystem)
        self.focus_every_master.setGeometry(QtCore.QRect(380, 162, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.focus_every_master.setFont(font)
        self.focus_every_master.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.focus_every_master.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.focus_every_master.setMinimum(0)
        self.focus_every_master.setMaximum(100)
        self.focus_every_master.setProperty("value", 1)
        self.focus_every_master.setObjectName("focus_every_master")
        self.master_image = QtWidgets.QLabel(self.masterSystem)
        self.master_image.setGeometry(QtCore.QRect(8, 330, 455, 250))
        self.master_image.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.master_image.setText("")
        self.master_image.setAlignment(QtCore.Qt.AlignCenter)
        self.master_image.setObjectName("master_image")
        self.label_164 = QtWidgets.QLabel(self.masterSystem)
        self.label_164.setGeometry(QtCore.QRect(10, 290, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_164.setFont(font)
        self.label_164.setObjectName("label_164")
        self.line_26 = QtWidgets.QFrame(self.masterSystem)
        self.line_26.setGeometry(QtCore.QRect(10, 310, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_26.setFont(font)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setObjectName("line_26")
        self.label_167 = QtWidgets.QLabel(self.masterSystem)
        self.label_167.setGeometry(QtCore.QRect(10, 40, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_167.setFont(font)
        self.label_167.setObjectName("label_167")
        self.line_27 = QtWidgets.QFrame(self.masterSystem)
        self.line_27.setGeometry(QtCore.QRect(10, 55, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_27.setFont(font)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setObjectName("line_27")
        self.line_30 = QtWidgets.QFrame(self.masterSystem)
        self.line_30.setGeometry(QtCore.QRect(10, 210, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_30.setFont(font)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setObjectName("line_30")
        self.label_168 = QtWidgets.QLabel(self.masterSystem)
        self.label_168.setGeometry(QtCore.QRect(10, 190, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_168.setFont(font)
        self.label_168.setObjectName("label_168")
        self.master_slew = QtWidgets.QPushButton(self.masterSystem)
        self.master_slew.setGeometry(QtCore.QRect(10, 230, 101, 34))
        self.master_slew.setObjectName("master_slew")
        self.master_focus = QtWidgets.QPushButton(self.masterSystem)
        self.master_focus.setGeometry(QtCore.QRect(120, 230, 101, 34))
        self.master_focus.setObjectName("master_focus")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 941, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.integration_time = QtWidgets.QSpinBox(self.groupBox)
        self.integration_time.setGeometry(QtCore.QRect(800, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.integration_time.setFont(font)
        self.integration_time.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.integration_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.integration_time.setMinimum(30)
        self.integration_time.setMaximum(10000000)
        self.integration_time.setProperty("value", 300)
        self.integration_time.setObjectName("integration_time")
        self.label_42 = QtWidgets.QLabel(self.groupBox)
        self.label_42.setGeometry(QtCore.QRect(680, 55, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.object_name = QtWidgets.QLineEdit(self.groupBox)
        self.object_name.setGeometry(QtCore.QRect(50, 50, 161, 32))
        self.object_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.object_name.setObjectName("object_name")
        self.label_175 = QtWidgets.QLabel(self.groupBox)
        self.label_175.setGeometry(QtCore.QRect(10, 10, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_175.setFont(font)
        self.label_175.setObjectName("label_175")
        self.line_29 = QtWidgets.QFrame(self.groupBox)
        self.line_29.setGeometry(QtCore.QRect(10, 30, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_29.setFont(font)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setObjectName("line_29")
        self.label_51 = QtWidgets.QLabel(self.groupBox)
        self.label_51.setGeometry(QtCore.QRect(10, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.ar = QtWidgets.QLineEdit(self.groupBox)
        self.ar.setGeometry(QtCore.QRect(270, 50, 161, 32))
        self.ar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ar.setObjectName("ar")
        self.label_52 = QtWidgets.QLabel(self.groupBox)
        self.label_52.setGeometry(QtCore.QRect(230, 50, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox)
        self.label_53.setGeometry(QtCore.QRect(450, 50, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.dec = QtWidgets.QLineEdit(self.groupBox)
        self.dec.setGeometry(QtCore.QRect(490, 50, 161, 32))
        self.dec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dec.setObjectName("dec")
        self.slaveSystem = QtWidgets.QGroupBox(self.centralwidget)
        self.slaveSystem.setGeometry(QtCore.QRect(470, 100, 470, 591))
        self.slaveSystem.setObjectName("slaveSystem")
        self.slave_profile = QtWidgets.QComboBox(self.slaveSystem)
        self.slave_profile.setGeometry(QtCore.QRect(10, 82, 101, 32))
        self.slave_profile.setObjectName("slave_profile")
        self.slave_profile.addItem("")
        self.slave_profile.addItem("")
        self.run_slave = QtWidgets.QPushButton(self.slaveSystem)
        self.run_slave.setGeometry(QtCore.QRect(120, 82, 101, 32))
        self.run_slave.setObjectName("run_slave")
        self.slave_bin = QtWidgets.QSpinBox(self.slaveSystem)
        self.slave_bin.setGeometry(QtCore.QRect(380, 72, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.slave_bin.setFont(font)
        self.slave_bin.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.slave_bin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slave_bin.setMinimum(1)
        self.slave_bin.setMaximum(4)
        self.slave_bin.setProperty("value", 1)
        self.slave_bin.setObjectName("slave_bin")
        self.label_49 = QtWidgets.QLabel(self.slaveSystem)
        self.label_49.setGeometry(QtCore.QRect(250, 102, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.slaveSystem)
        self.label_50.setGeometry(QtCore.QRect(250, 72, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_172 = QtWidgets.QLabel(self.slaveSystem)
        self.label_172.setGeometry(QtCore.QRect(250, 40, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_172.setFont(font)
        self.label_172.setObjectName("label_172")
        self.line_28 = QtWidgets.QFrame(self.slaveSystem)
        self.line_28.setGeometry(QtCore.QRect(250, 55, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_28.setFont(font)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setObjectName("line_28")
        self.slave_host = QtWidgets.QLineEdit(self.slaveSystem)
        self.slave_host.setGeometry(QtCore.QRect(10, 142, 101, 32))
        self.slave_host.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slave_host.setObjectName("slave_host")
        self.slave_port = QtWidgets.QLineEdit(self.slaveSystem)
        self.slave_port.setGeometry(QtCore.QRect(120, 142, 101, 32))
        self.slave_port.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slave_port.setObjectName("slave_port")
        self.label_173 = QtWidgets.QLabel(self.slaveSystem)
        self.label_173.setGeometry(QtCore.QRect(10, 122, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_173.setFont(font)
        self.label_173.setObjectName("label_173")
        self.label_174 = QtWidgets.QLabel(self.slaveSystem)
        self.label_174.setGeometry(QtCore.QRect(120, 122, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_174.setFont(font)
        self.label_174.setObjectName("label_174")
        self.slave_single_exposure = QtWidgets.QSpinBox(self.slaveSystem)
        self.slave_single_exposure.setGeometry(QtCore.QRect(380, 102, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.slave_single_exposure.setFont(font)
        self.slave_single_exposure.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.slave_single_exposure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slave_single_exposure.setMinimum(0)
        self.slave_single_exposure.setMaximum(10000000)
        self.slave_single_exposure.setProperty("value", 5)
        self.slave_single_exposure.setObjectName("slave_single_exposure")
        self.focus_every_slave = QtWidgets.QSpinBox(self.slaveSystem)
        self.focus_every_slave.setGeometry(QtCore.QRect(380, 132, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.focus_every_slave.setFont(font)
        self.focus_every_slave.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.focus_every_slave.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.focus_every_slave.setMinimum(0)
        self.focus_every_slave.setMaximum(100)
        self.focus_every_slave.setProperty("value", 1)
        self.focus_every_slave.setObjectName("focus_every_slave")
        self.fo = QtWidgets.QLabel(self.slaveSystem)
        self.fo.setGeometry(QtCore.QRect(250, 132, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fo.setFont(font)
        self.fo.setObjectName("fo")
        self.slave_image = QtWidgets.QLabel(self.slaveSystem)
        self.slave_image.setGeometry(QtCore.QRect(8, 330, 455, 250))
        self.slave_image.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.slave_image.setText("")
        self.slave_image.setAlignment(QtCore.Qt.AlignCenter)
        self.slave_image.setObjectName("slave_image")
        self.line_31 = QtWidgets.QFrame(self.slaveSystem)
        self.line_31.setGeometry(QtCore.QRect(10, 310, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_31.setFont(font)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setObjectName("line_31")
        self.label_169 = QtWidgets.QLabel(self.slaveSystem)
        self.label_169.setGeometry(QtCore.QRect(10, 290, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_169.setFont(font)
        self.label_169.setObjectName("label_169")
        self.label_170 = QtWidgets.QLabel(self.slaveSystem)
        self.label_170.setGeometry(QtCore.QRect(10, 40, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_170.setFont(font)
        self.label_170.setObjectName("label_170")
        self.line_32 = QtWidgets.QFrame(self.slaveSystem)
        self.line_32.setGeometry(QtCore.QRect(10, 55, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_32.setFont(font)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setObjectName("line_32")
        self.label_171 = QtWidgets.QLabel(self.slaveSystem)
        self.label_171.setGeometry(QtCore.QRect(10, 190, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_171.setFont(font)
        self.label_171.setObjectName("label_171")
        self.slave_focus = QtWidgets.QPushButton(self.slaveSystem)
        self.slave_focus.setGeometry(QtCore.QRect(120, 230, 101, 34))
        self.slave_focus.setObjectName("slave_focus")
        self.line_33 = QtWidgets.QFrame(self.slaveSystem)
        self.line_33.setGeometry(QtCore.QRect(10, 210, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_33.setFont(font)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setObjectName("line_33")
        self.slave_slew = QtWidgets.QPushButton(self.slaveSystem)
        self.slave_slew.setGeometry(QtCore.QRect(10, 230, 101, 34))
        self.slave_slew.setObjectName("slave_slew")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(800, 700, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.log = QtWidgets.QLabel(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(10, 700, 781, 71))
        self.log.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.log.setObjectName("log")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(800, 740, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.stop.setFont(font)
        self.stop.setObjectName("stop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_SaaS = QtWidgets.QAction(MainWindow)
        self.actionAbout_SaaS.setObjectName("actionAbout_SaaS")
        self.actionSequence_options = QtWidgets.QAction(MainWindow)
        self.actionSequence_options.setObjectName("actionSequence_options")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout_SaaS)
        self.menuSettings.addAction(self.actionSequence_options)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.master_profile.setCurrentIndex(0)
        self.slave_profile.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SaaS for CCDCiel"))
        self.masterSystem.setTitle(_translate("MainWindow", "Master node"))
        self.master_profile.setItemText(0, _translate("MainWindow", "QHY42"))
        self.master_profile.setItemText(1, _translate("MainWindow", "QHY268"))
        self.run_master.setText(_translate("MainWindow", "Run"))
        self.master_bin.setToolTip(_translate("MainWindow", "sets the camera bin"))
        self.label_39.setText(_translate("MainWindow", "Single exposure (s)"))
        self.label_40.setText(_translate("MainWindow", "Camera bin"))
        self.label_163.setText(_translate("MainWindow", "Frame settings"))
        self.master_host.setText(_translate("MainWindow", "localhost"))
        self.master_port.setText(_translate("MainWindow", "3277"))
        self.label_165.setText(_translate("MainWindow", "Server"))
        self.label_166.setText(_translate("MainWindow", "Port"))
        self.master_single_exposure.setToolTip(_translate("MainWindow", "sets the exposure time"))
        self.label_41.setText(_translate("MainWindow", "Dither (frames)"))
        self.dither_every.setToolTip(_translate("MainWindow", "sets the exposure time"))
        self.fo_2.setText(_translate("MainWindow", "Autofocus (frames)"))
        self.focus_every_master.setToolTip(_translate("MainWindow", "sets the exposure time"))
        self.label_164.setText(_translate("MainWindow", "Latest image from master"))
        self.label_167.setText(_translate("MainWindow", "CCDCiel profile"))
        self.label_168.setText(_translate("MainWindow", "Pre-sequence actions"))
        self.master_slew.setText(_translate("MainWindow", "Slew and sync"))
        self.master_focus.setText(_translate("MainWindow", "Focus"))
        self.integration_time.setToolTip(_translate("MainWindow", "sets the camera bin"))
        self.label_42.setText(_translate("MainWindow", "Integration (s)"))
        self.object_name.setText(_translate("MainWindow", "Object Name"))
        self.label_175.setText(_translate("MainWindow", "Target properties"))
        self.label_51.setText(_translate("MainWindow", "Name"))
        self.ar.setText(_translate("MainWindow", "00:00:00"))
        self.label_52.setText(_translate("MainWindow", "AR"))
        self.label_53.setText(_translate("MainWindow", "DEC"))
        self.dec.setText(_translate("MainWindow", "00:00:00"))
        self.slaveSystem.setTitle(_translate("MainWindow", "Slave node"))
        self.slave_profile.setItemText(0, _translate("MainWindow", "QHY42"))
        self.slave_profile.setItemText(1, _translate("MainWindow", "QHY268"))
        self.run_slave.setText(_translate("MainWindow", "Run"))
        self.slave_bin.setToolTip(_translate("MainWindow", "sets the camera bin"))
        self.label_49.setText(_translate("MainWindow", "Single exposure (s)"))
        self.label_50.setText(_translate("MainWindow", "Camera bin"))
        self.label_172.setText(_translate("MainWindow", "Frame settings"))
        self.slave_host.setText(_translate("MainWindow", "localhost"))
        self.slave_port.setText(_translate("MainWindow", "3277"))
        self.label_173.setText(_translate("MainWindow", "Server"))
        self.label_174.setText(_translate("MainWindow", "Port"))
        self.slave_single_exposure.setToolTip(_translate("MainWindow", "sets the exposure time"))
        self.focus_every_slave.setToolTip(_translate("MainWindow", "sets the exposure time"))
        self.fo.setText(_translate("MainWindow", "Autofocus (frames)"))
        self.label_169.setText(_translate("MainWindow", "Latest image from slave"))
        self.label_170.setText(_translate("MainWindow", "CCDCiel profile"))
        self.label_171.setText(_translate("MainWindow", "Pre-sequence actions"))
        self.slave_focus.setText(_translate("MainWindow", "Focus"))
        self.slave_slew.setText(_translate("MainWindow", "Slew and sync"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.log.setText(_translate("MainWindow", "TextLabel"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settin&gs"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionAbout_SaaS.setText(_translate("MainWindow", "&About SaaS"))
        self.actionSequence_options.setText(_translate("MainWindow", "Sequence options"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
