# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sequence_options_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SequenceOptions(object):
    def setupUi(self, SequenceOptions):
        SequenceOptions.setObjectName("SequenceOptions")
        SequenceOptions.resize(457, 293)
        self.buttonBox = QtWidgets.QDialogButtonBox(SequenceOptions)
        self.buttonBox.setGeometry(QtCore.QRect(110, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.slaveSystem_2 = QtWidgets.QGroupBox(SequenceOptions)
        self.slaveSystem_2.setGeometry(QtCore.QRect(10, 10, 441, 231))
        self.slaveSystem_2.setTitle("")
        self.slaveSystem_2.setObjectName("slaveSystem_2")
        self.label_7 = QtWidgets.QLabel(self.slaveSystem_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.autofocus_master = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.autofocus_master.setGeometry(QtCore.QRect(40, 100, 171, 22))
        self.autofocus_master.setObjectName("autofocus_master")
        self.use_autoguiding_slave = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.use_autoguiding_slave.setGeometry(QtCore.QRect(40, 80, 171, 22))
        self.use_autoguiding_slave.setObjectName("use_autoguiding_slave")
        self.autofocus_slave = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.autofocus_slave.setGeometry(QtCore.QRect(40, 120, 171, 22))
        self.autofocus_slave.setObjectName("autofocus_slave")
        self.use_autoguiding_master = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.use_autoguiding_master.setGeometry(QtCore.QRect(40, 60, 171, 22))
        self.use_autoguiding_master.setObjectName("use_autoguiding_master")
        self.autofocus_slave_2 = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.autofocus_slave_2.setGeometry(QtCore.QRect(230, 40, 171, 22))
        self.autofocus_slave_2.setObjectName("autofocus_slave_2")
        self.autofocus_slave_3 = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.autofocus_slave_3.setGeometry(QtCore.QRect(230, 70, 171, 22))
        self.autofocus_slave_3.setObjectName("autofocus_slave_3")
        self.autofocus_slave_4 = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.autofocus_slave_4.setGeometry(QtCore.QRect(230, 100, 171, 22))
        self.autofocus_slave_4.setObjectName("autofocus_slave_4")
        self.autofocus_slave_5 = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.autofocus_slave_5.setGeometry(QtCore.QRect(230, 120, 171, 22))
        self.autofocus_slave_5.setObjectName("autofocus_slave_5")
        self.autofocus_slave_6 = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.autofocus_slave_6.setGeometry(QtCore.QRect(40, 150, 371, 22))
        self.autofocus_slave_6.setObjectName("autofocus_slave_6")
        self.autofocus_slave_7 = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.autofocus_slave_7.setGeometry(QtCore.QRect(80, 170, 371, 22))
        self.autofocus_slave_7.setObjectName("autofocus_slave_7")
        self.autofocus_slave_8 = QtWidgets.QCheckBox(self.slaveSystem_2)
        self.autofocus_slave_8.setGeometry(QtCore.QRect(80, 190, 371, 22))
        self.autofocus_slave_8.setObjectName("autofocus_slave_8")

        self.retranslateUi(SequenceOptions)
        self.buttonBox.accepted.connect(SequenceOptions.accept)
        self.buttonBox.rejected.connect(SequenceOptions.reject)
        QtCore.QMetaObject.connectSlotsByName(SequenceOptions)

    def retranslateUi(self, SequenceOptions):
        _translate = QtCore.QCoreApplication.translate
        SequenceOptions.setWindowTitle(_translate("SequenceOptions", "Dialog"))
        self.label_7.setText(_translate("SequenceOptions", "General Options"))
        self.autofocus_master.setText(_translate("SequenceOptions", "Autofocus master"))
        self.use_autoguiding_slave.setText(_translate("SequenceOptions", "Autoguide from slave"))
        self.autofocus_slave.setText(_translate("SequenceOptions", "Autofocus slave"))
        self.use_autoguiding_master.setText(_translate("SequenceOptions", "Autoguide from master"))
        self.autofocus_slave_2.setText(_translate("SequenceOptions", "Autoconnect devices"))
        self.autofocus_slave_3.setText(_translate("SequenceOptions", "Warm camera"))
        self.autofocus_slave_4.setText(_translate("SequenceOptions", "Close shuter"))
        self.autofocus_slave_5.setText(_translate("SequenceOptions", "Run command"))
        self.autofocus_slave_6.setText(_translate("SequenceOptions", "Capture calibration frames at the end"))
        self.autofocus_slave_7.setText(_translate("SequenceOptions", "User filter"))
        self.autofocus_slave_8.setText(_translate("SequenceOptions", "Close shuter before "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SequenceOptions = QtWidgets.QDialog()
    ui = Ui_SequenceOptions()
    ui.setupUi(SequenceOptions)
    SequenceOptions.show()
    sys.exit(app.exec_())
