# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slave_advanced_options.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SlaveAdvancedOptions(object):
    def setupUi(self, SlaveAdvancedOptions):
        SlaveAdvancedOptions.setObjectName("SlaveAdvancedOptions")
        SlaveAdvancedOptions.resize(284, 149)
        self.gridLayout = QtWidgets.QGridLayout(SlaveAdvancedOptions)
        self.gridLayout.setObjectName("gridLayout")
        self.label_177 = QtWidgets.QLabel(SlaveAdvancedOptions)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_177.setFont(font)
        self.label_177.setObjectName("label_177")
        self.gridLayout.addWidget(self.label_177, 0, 0, 1, 1)
        self.label_165 = QtWidgets.QLabel(SlaveAdvancedOptions)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_165.setFont(font)
        self.label_165.setObjectName("label_165")
        self.gridLayout.addWidget(self.label_165, 1, 0, 1, 1)
        self.label_166 = QtWidgets.QLabel(SlaveAdvancedOptions)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_166.setFont(font)
        self.label_166.setObjectName("label_166")
        self.gridLayout.addWidget(self.label_166, 1, 1, 1, 1)
        self.line_35 = QtWidgets.QFrame(SlaveAdvancedOptions)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_35.setFont(font)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setObjectName("line_35")
        self.gridLayout.addWidget(self.line_35, 2, 0, 1, 2)
        self.slave_host = QtWidgets.QLineEdit(SlaveAdvancedOptions)
        self.slave_host.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slave_host.setObjectName("slave_host")
        self.gridLayout.addWidget(self.slave_host, 3, 0, 1, 1)
        self.slave_port = QtWidgets.QLineEdit(SlaveAdvancedOptions)
        self.slave_port.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slave_port.setObjectName("slave_port")
        self.gridLayout.addWidget(self.slave_port, 3, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(SlaveAdvancedOptions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 2)

        self.retranslateUi(SlaveAdvancedOptions)
        self.buttonBox.accepted.connect(SlaveAdvancedOptions.accept)
        self.buttonBox.rejected.connect(SlaveAdvancedOptions.reject)
        QtCore.QMetaObject.connectSlotsByName(SlaveAdvancedOptions)

    def retranslateUi(self, SlaveAdvancedOptions):
        _translate = QtCore.QCoreApplication.translate
        SlaveAdvancedOptions.setWindowTitle(_translate("SlaveAdvancedOptions", "Advanced Options (Slave)"))
        self.label_177.setText(_translate("SlaveAdvancedOptions", "CCDCiel host"))
        self.label_165.setText(_translate("SlaveAdvancedOptions", "Server"))
        self.label_166.setText(_translate("SlaveAdvancedOptions", "Port"))
        self.slave_host.setText(_translate("SlaveAdvancedOptions", "localhost"))
        self.slave_port.setText(_translate("SlaveAdvancedOptions", "3278"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SlaveAdvancedOptions = QtWidgets.QDialog()
    ui = Ui_SlaveAdvancedOptions()
    ui.setupUi(SlaveAdvancedOptions)
    SlaveAdvancedOptions.show()
    sys.exit(app.exec_())
