# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wait.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wait(object):
    def setupUi(self, Wait):
        Wait.setObjectName("Wait")
        Wait.resize(370, 112)
        self.gridLayout = QtWidgets.QGridLayout(Wait)
        self.gridLayout.setObjectName("gridLayout")
        self.msg = QtWidgets.QLabel(Wait)
        self.msg.setObjectName("msg")
        self.gridLayout.addWidget(self.msg, 0, 0, 1, 1)

        self.retranslateUi(Wait)
        QtCore.QMetaObject.connectSlotsByName(Wait)

    def retranslateUi(self, Wait):
        _translate = QtCore.QCoreApplication.translate
        Wait.setWindowTitle(_translate("Wait", "Please wait..."))
        self.msg.setText(_translate("Wait", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wait = QtWidgets.QDialog()
    ui = Ui_Wait()
    ui.setupUi(Wait)
    Wait.show()
    sys.exit(app.exec_())
